sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t brucejmcclure/docker-ci -f Docerfile.dev .

script:
  - docker run -e CI=true brucejmcclure/docker-ci npm run test
#
